-
  name: Router show commands
  hosts: router
  gather_facts: no
  connection: local
  tasks:
     - name: Show version command
       ios_command:
         commands:
            - sho version
       register: version
     - name: Display result of show version
       debug:
         var: version

     
