-
  name: Test connectivity
  hosts: all
  gather_facts: no
  connection: local
  tasks:
     - name: Show version command
       ios_command:
         commands:
            - show version
#            - show interfaces
