-
  name: Router show commands
  hosts: all
  gather_facts: no
  connection: local
  tasks:
     - name: Show version command
       ios_command:
         commands:
#            - show version
            - sho ip int brief
#       register: version
       register: interfaces
     - name: Display result of show version
       debug:
#         var: version1
         var: interfaces
