---
-
  name: Configure a router
  hosts: router
  gather_facts: no
  connection: local
  tasks:
    - name: add a config line command
      ios_config:
          lines:
             - username test1 password test1
             - interface loopback 0
             - ip add 1.1.1.1 255.255.255.255
             - hostname AnSiBlE
      register: var1
    - name: Display results of above
      debug:
        var: var1
    - name: add another set of commands
      ios_config:
          lines:
             - username test2 password test2
      register: var2
    - name: Display results of above
      debug:
        var: var2
